# SPDX-FileCopyrightText: 2023-2026 Sayantan Santra <sayantan.santra689@gmail.com>
# SPDX-License-Identifier: MIT

FROM alpine AS builder
COPY ./backend/target/x86_64-unknown-linux-musl/debug/chhoto-url /app/chhoto-url

ARG TARGETARCH
FROM builder
RUN apk add --no-cache tzdata
RUN mkdir -p /app/frontend/final

WORKDIR /app
ENTRYPOINT ["/app/chhoto-url"]

