# SPDX-FileCopyrightText: 2023-2026 Sayantan Santra <sayantan.santra689@gmail.com>
# SPDX-License-Identifier: MIT

FROM scratch AS builder-amd64
COPY ./backend/target/x86_64-unknown-linux-musl/release/chhoto-url /chhoto-url

FROM scratch AS builder-arm64
COPY ./backend/target/aarch64-unknown-linux-musl/release/chhoto-url /chhoto-url

FROM scratch AS builder-arm
COPY ./backend/target/armv7-unknown-linux-musleabihf/release/chhoto-url /chhoto-url

FROM scratch AS builder-riscv64
COPY ./backend/target/riscv64gc-unknown-linux-musl/release/chhoto-url /chhoto-url

ARG TARGETARCH
FROM builder-$TARGETARCH
COPY ./frontend /frontend

ENTRYPOINT ["/chhoto-url"]

