name: Tests

on:
  push:
    branches: ["*"]
    paths: ["backend/**"]
  pull_request:
    branches: ["*"]
  workflow_dispatch:

env:
  CARGO_TERM_COLOR: always

jobs:
  test:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./backend
    steps:
      - uses: actions/checkout@v6
      - name: Cache Dependencies
        uses: actions/cache@v5
        with:
          path: |
            backend/target
            backend/.cargo
          key: cargo-${{ runner.os }}-${{ hashFiles('backend/Cargo.lock') }}
          restore-keys: |
            cargo-${{ runner.os }}-
      - name: Build
        run: cargo build
      - name: Run tests
        run: cargo test
